=== viskiarditia/ALTA_QE9_TODOIST_TEAM-1/src/test/resources/feature/JSON/JSONSchema/GetCommentSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "project_id": {
      "type": "null"
    },
    "content": {
      "type": "string"
    },
    "posted_at": {
      "type": "string"
    },
    "attachment": {
      "type": "object",
      "properties": {
        "file_name": {
          "type": "string"
        },
        "file_type": {
          "type": "string"
        },
        "file_url": {
          "type": "string"
        }
      },
      "required": [
        "file_name",
        "file_type",
        "file_url"
      ]
    }
  },
  "required": [
    "id",
    "task_id",
    "project_id",
    "content",
    "posted_at",
    "attachment"
  ]
}

=== viskiarditia/ALTA_QE9_TODOIST_TEAM-1/src/test/resources/feature/JSON/JSONSchema/CreateNewCommentSchema.json
{
  "id": "3225180458",
  "task_id": "6614134187",
  "project_id": null,
  "content": "Need one bottle of milk",
  "posted_at": "2023-02-16T06:08:31.291980Z",
  "attachment": {
    "file_name": "File.pdf",
    "file_type": "application/pdf",
    "file_url": "https://s3.amazonaws.com/domorebetter/Todoist+Setup+Guide.pdf"
  }
}
